[[plugins]]
package = "netlify-plugin-submit-sitemap"
  [plugins.inputs]
  baseUrl = "https://slash-tmp.dev"
  sitemapPath = "/sitemap.xml"
  providers = [
    "google",
    "bing",
    "yandex"
  ]

[[headers]]
  for = "/*"
  [headers.values]
    # Content-Security-Policy = "default-src 'self'"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload" 